# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd07c731a76b5a7445d627d3271ff815f9c3ba29395ea832229acd120934b21ef11689d65d5193216293d48758041323d4a399132eb4beea2c0983fb4ab9b466

test:
  secret_key_base: cedb1ad6cbd26170c74969bf27e03818477ee3fd1e1e962f2a8153bd89e0588db4d01c735d53f0424aede47d5763fe6a635269b8d5ec1abfc3749f3bf3fc605c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
